export const metadata = {
    title: "Next.js",
    description: "Generated by Next JS"   
}

export default function RootLayout({
    children,

}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="eng">
            <body>{children}</body>
        </html>
    )
}   